# Generated by Django 4.1.3 on 2022-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
