# Generated by Django 4.1.3 on 2022-11-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bookings', '0002_alter_show_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaseats',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_name_for_booking', to='movie_bookings.city'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='movie_bookings/static/'),
        ),
    ]
