# Generated by Django 4.1.3 on 2022-11-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bookings', '0004_show_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaseats',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_movie_date', to='movie_bookings.show'),
        ),
    ]
