# Generated by Django 4.1.3 on 2022-11-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bookings', '0005_cinemaseats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
