# Generated by Django 4.1.3 on 2022-11-28 12:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bookings', '0006_show_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaseats',
            name='booked_seats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
