# Generated by Django 4.1.3 on 2022-11-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bookings', '0007_cinemaseats_booked_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaseats',
            name='final_price',
            field=models.FloatField(default=0),
        ),
    ]
