# Generated by Django 4.1.3 on 2022-11-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bookings', '0008_cinemaseats_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemaseats',
            name='date',
        ),
    ]
