# Generated by Django 4.1.3 on 2022-12-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_bookings', '0009_remove_cinemaseats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaseats',
            name='amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
